// a = "Hello World! It's JavaScript!";
// console.log(a);
// alert("Hello World! It's JavaScript!");
// document.write("Hello World! It's JavaScript!");
var a = 5;
var b = 2;
var c = 3;
var d = 0;
var e =0;
var g = 9;
var i ="10";
alert(4+6);
d =a*b;
alert(d);
e = e +10;
alert(e);
f = (d -e)*b+10;
alert (f);
h = ++g;
alert(h);
var k =Number(i);
alert(k);
